### ISSUE TITLE
runtimeerror

### ISSUE THREAD

**Issue by AK391** [Kazuhito00/AnimeGANv2-ONNX-Sample#1]
runs fine in colab but get this error running on a huggingface space

Traceback (most recent call last):
  File "app.py", line 7, in <module>
    onnx_session = onnxruntime.InferenceSession("/home/user/app/face_paint_512_v2_0.onnx")
  File "/home/user/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/user/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
RuntimeError: /onnxruntime_src/onnxruntime/core/platform/posix/env.cc:173 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 0 error msg:

**Comment by AK391** [comment]
resolved with 



opts = onnxruntime.SessionOptions()
opts.intra_op_num_threads = 8
onnx_session = onnxruntime.InferenceSession("face_paint_512_v2_0.onnx",sess_options=opts)
